-- Step 1: Add a sequence starting at 1111 for team codes
CREATE SEQUENCE IF NOT EXISTS team_code_seq START 1111 INCREMENT BY 1;

-- Step 2: Add team_code column to teams table
ALTER TABLE public.teams 
  ADD COLUMN IF NOT EXISTS team_code VARCHAR(20) UNIQUE;

-- Step 3: Create a function to auto-generate team_code on insert
CREATE OR REPLACE FUNCTION generate_team_code()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.team_code IS NULL THEN
    NEW.team_code := 'ST-' || LPAD(nextval('team_code_seq')::TEXT, 4, '0');
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Step 4: Attach trigger to teams table
DROP TRIGGER IF EXISTS trg_team_code ON public.teams;
CREATE TRIGGER trg_team_code
  BEFORE INSERT ON public.teams
  FOR EACH ROW EXECUTE FUNCTION generate_team_code();

-- Step 5: Seed initial rows (team_code auto-generated by trigger)
INSERT INTO public.teams (id, name, city, state, country, matches_played, matches_won, matches_lost)
VALUES
  (uuid_generate_v4(), 'Storm Riders',    'Mumbai',    'Maharashtra', 'India', 0, 0, 0),
  (uuid_generate_v4(), 'Knights United',  'Mumbai',    'Maharashtra', 'India', 0, 0, 0),
  (uuid_generate_v4(), 'Titans Strikers', 'Ahmedabad', 'Gujarat',     'India', 0, 0, 0);
