import 'dart:typed_data';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import '../../services/database.dart';

class PdfGenerator {
  static Future<Uint8List> generateScorecard(CricketMatch match) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Header(
                level: 0,
                child: pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                  children: [
                    pw.Text(
                      'SCORELY SCORECARD',
                      style: pw.TextStyle(
                        fontWeight: pw.FontWeight.bold,
                        fontSize: 24,
                      ),
                    ),
                    pw.Text(match.createdAt.toString().split(' ')[0]),
                  ],
                ),
              ),
              pw.SizedBox(height: 20),
              pw.Text(
                match.matchTitle.toUpperCase(),
                style: pw.TextStyle(
                  fontSize: 18,
                  fontWeight: pw.FontWeight.bold,
                ),
              ),
              pw.SizedBox(height: 10),
              pw.Divider(),
              pw.SizedBox(height: 10),

              pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  _teamScoreBox(
                    'TEAM A',
                    '${match.teamARuns}/${match.teamAWickets}',
                    '(${match.teamAOvers}.${match.teamABalls})',
                  ),
                  pw.Text(
                    'VS',
                    style: pw.TextStyle(fontSize: 14, color: PdfColors.grey),
                  ),
                  _teamScoreBox(
                    'TEAM B',
                    '${match.teamBRuns}/${match.teamBWickets}',
                    '(${match.teamBOvers}.${match.teamBBalls})',
                  ),
                ],
              ),

              pw.SizedBox(height: 30),
              pw.Text(
                'RESULT: ${match.winnerTeamName ?? "DRAW"}',
                style: pw.TextStyle(
                  fontSize: 16,
                  fontWeight: pw.FontWeight.bold,
                ),
              ),

              pw.SizedBox(height: 30),
              pw.Text(
                'BATTING STATS',
                style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
              ),
              pw.TableHelper.fromTextArray(
                context: context,
                data: [
                  ['PLAYER', 'RUNS', 'BALLS', '4s', '6s', 'SR'],
                  ['Player 1', '45', '30', '4', '2', '150.0'],
                  ['Player 2', '12', '15', '1', '0', '80.0'],
                ],
              ),

              pw.SizedBox(height: 30),
              pw.Text(
                'BOWLING STATS',
                style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
              ),
              pw.TableHelper.fromTextArray(
                context: context,
                data: [
                  ['BOWLER', 'O', 'M', 'R', 'W', 'ECON'],
                  ['Bowler 1', '4.0', '0', '24', '2', '6.0'],
                  ['Bowler 2', '4.0', '0', '32', '1', '8.0'],
                ],
              ),

              pw.Spacer(),
              pw.Align(
                alignment: pw.Alignment.center,
                child: pw.Text(
                  'Generated by Scorely Velocity System',
                  style: pw.TextStyle(color: PdfColors.grey700, fontSize: 10),
                ),
              ),
            ],
          );
        },
      ),
    );

    return pdf.save();
  }

  static pw.Widget _teamScoreBox(String name, String score, String overs) {
    return pw.Column(
      children: [
        pw.Text(name, style: const pw.TextStyle(fontSize: 12)),
        pw.Text(
          score,
          style: pw.TextStyle(fontSize: 20, fontWeight: pw.FontWeight.bold),
        ),
        pw.Text(overs, style: const pw.TextStyle(fontSize: 10)),
      ],
    );
  }
}
